{% set name = "msmtools" %}
{% set version = "1.2.5" %}
{% set sha256 = "e07b73ad9e4e8ef8aca82e6b5bb55f57f8400a65fb2fd656b521f72237a7310a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -v"
  skip: True  # [py27 or python_impl == 'pypy']

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - cython >=0.24
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - six
    - decorator

test:
  imports:
    - msmtools 

about:
  home: http://github.com/markovmodel/msmtools
  license: LGPL-3.0-or-later 
  license_file: LICENSE.txt
  summary: 'Tools for estimating and analyzing Markov state models'
  description: |
    'msmtools is an open source collection of algorithms for the estimation
     and analysis of discrete state space Markov chains via Markov state models (MSM)'

extra:
  recipe-maintainers:
    - marscher
    - clonker
